name: Feature request
description: An idea for the website or the firmware.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would you like to happen?
    validations:
      required: true
  - type: checkboxes
    id: help
    attributes:
      label: Contributing
      options:
        - label: I would like to work on this myself
