#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
#
# Build Keyforge firmware: pico-fido (firmware/pico-fido, pinned submodule)
# plus the patches in firmware/patches. Used by CI and for local custom builds.
#
#   firmware/build.sh <board> [<board> ...]
#
# Boards: pico, pico2, any other pico-sdk board name (e.g. waveshare_rp2040_zero),
#         esp32s3, esp32s2.
#
# Environment (all optional):
#   VERSION                    label for file names (default: upstream tag, e.g. 8.0)
#   OUT                        output directory (default: firmware/dist)
#   PICO_SDK_PATH              pico-sdk checkout (required for RP boards)
#   MAX_RESIDENT_CREDENTIALS   passkey slots, 1..256 (default 256, firmware limit)
#   ENABLE_OATH_APP            1/0, OATH (TOTP/HOTP) applet (default 1)
#   ENABLE_OTP_APP             1/0, Yubico-style OTP applet (default 1)
#                              Keyforge's Configure and Passkeys pages need at least
#                              one of the two: they enable the USB smart-card interface.
#   ENABLE_POWER_ON_RESET      1/0 (default: upstream default)
#   SECURE_BOOT_PKEY           PEM private key to sign RP2350 images with YOUR key.
#                              Never commit it. Unsigned if unset.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/pico-fido"
out="${OUT:-$here/dist}"

[ "$#" -gt 0 ] || { sed -n '5,25p' "$0"; exit 2; }
[ -f "$src/CMakeLists.txt" ] || { echo "Missing $src. Run: git submodule update --init --recursive" >&2; exit 1; }

if [ -z "${VERSION:-}" ]; then
  if [ -f "$here/VERSION" ]; then
    VERSION="$(tr -d ' \r\n' < "$here/VERSION")"
  else
    VERSION="$(git -C "$src" describe --tags --exact-match 2>/dev/null || git -C "$src" rev-parse --short HEAD)"
    VERSION="${VERSION#v}"
  fi
fi

max="${MAX_RESIDENT_CREDENTIALS:-256}"
if ! [[ "$max" =~ ^[0-9]+$ ]] || [ "$max" -lt 1 ] || [ "$max" -gt 256 ]; then
  echo "MAX_RESIDENT_CREDENTIALS must be 1..256 (credential file IDs stop at 0xCFFF)." >&2
  exit 1
fi

# Work on a throwaway copy so the submodule stays pristine.
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
cp -a "$src/." "$work/"
# Submodule .git files point back into this repo; drop them so the copy is plain source.
find "$work" -name .git -prune -exec rm -rf {} +
for p in "$here"/patches/*.patch; do
  [ -e "$p" ] || continue
  echo "Applying $(basename "$p")"
  # --ignore-whitespace also copes with CRLF checkouts (Windows + Docker bind mounts).
  git -C "$work" apply --ignore-whitespace --whitespace=nowarn "$p"
done
cat > "$work/src/fido/keyforge_config.h" <<EOF
/* Generated by firmware/build.sh. */
#define MAX_RESIDENT_CREDENTIALS ${max}
#define KEYFORGE_BUILD "${VERSION}"
EOF

opts=()
for o in ENABLE_OATH_APP ENABLE_OTP_APP ENABLE_POWER_ON_RESET; do
  [ -n "${!o:-}" ] && opts+=("-D$o=${!o}")
done

mkdir -p "$out"
for board in "$@"; do
  echo "=== $board ($VERSION)"
  case "$board" in
    esp32s3|esp32s2)
      : "${IDF_PATH:?ESP builds need ESP-IDF 5.5 (source export.sh, or use the Docker image)}"
      chip="ESP32-${board#esp32}"; chip="${chip^^}"
      label="esp32-${board#esp32}"
      rm -rf "$work/build" "$work/sdkconfig"
      (cd "$work" && idf.py "${opts[@]}" set-target "$board" && idf.py "${opts[@]}" build)
      (cd "$work/build" && esptool.py --chip "$chip" merge_bin -o "$out/keyforge-fido_${label}-${VERSION}.bin" @flash_args)
      ;;
    *)
      : "${PICO_SDK_PATH:?RP builds need PICO_SDK_PATH (pico-sdk 2.1.1)}"
      sign=()
      [ -n "${SECURE_BOOT_PKEY:-}" ] && sign=("-DSECURE_BOOT_PKEY=$SECURE_BOOT_PKEY")
      b="$work/build_$board"
      cmake -S "$work" -B "$b" -DPICO_SDK_PATH="$PICO_SDK_PATH" -DPICO_BOARD="$board" "${opts[@]}" "${sign[@]}"
      cmake --build "$b" -j"$(nproc 2>/dev/null || sysctl -n hw.ncpu)"
      cp "$b/pico_fido.uf2" "$out/keyforge-fido_${board}-${VERSION}.uf2"
      ;;
  esac
done

(cd "$out" && ls -1 keyforge-fido_* | xargs sha256sum > SHA256SUMS && cat SHA256SUMS)
